name: ci

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Check
        env:
          OPENOBSERVE_URL: ${{ secrets.OPENOBSERVE_URL }}
          OPENOBSERVE_TOKEN: ${{ secrets.OPENOBSERVE_TOKEN }}
        run: deno task all
